### ISSUE TITLE
Is it expected dot (.) to work?

### ISSUE THREAD

**Issue by himanshutank-sophos** [glts/vim-radical#16]
I have installed radical.
I have installed magnum.
I have installed repeat.
gA works for me with no issue. Since in the documentation "repeat.vim" is mentioned, I tried doing dot (.) to repeat the command "gA" but it didn't work for me.

Is this a feature? Should we expect it to work?

I am using NVIM v0.8.2.

**Comment by glts** [comment]
The dot command only repeats the last change, see `:h .`. In radical.vim it repeats the coercion commands.

It doesn’t repeat commands that simply print something like `ga`, `g8`, `CTRL-G` – or radical.vim’s `gA`.

So this is working as intended.
