### ISSUE TITLE
Why only digits?

### ISSUE THREAD

**Issue by elig0n** [glts/vim-radical#5]
It was cool if this could do characters as well

**Comment by glts** [comment]
Well, I originally made this because I sometimes needed to convert between integer literals in C – that plus binary.

– But I don’t really understand your question.

**Comment by alerque** [comment]
This supports hexidecimal numbers, but only recognizes `0xNN` format by default and only outputs that in return. I think @elig0n probably had the same expectation I did of being able to convert things like HEX numbers as found in CSS colors.

* `0xF1` → <kbd>c</kbd><kbd>r</kbd><kbd>x</kbd> = `241`
* `F1` → <kbd>c</kbd><kbd>r</kbd><kbd>x</kbd> = `F1`

It does work, but you have to use:

* `F1` → <kbd>1</kbd><kbd>6</kbd><kbd>c</kbd><kbd>r</kbd><kbd>x</kbd> = `241`

...and there doesn't appear to be any way to change the output format to not be `0xNN`.

**Comment by glts** [comment]
@alerque Yeah, the behaviour in your example is intentional.

But I agree that this should be more flexible or customisable, for example by taking into account a buffer-local variable with the input and output formats …

**Comment by glts** [comment]
I’ve added support for customising coercion output.

Closing this as it’s unclear, but more can be done in the future.
