### ISSUE TITLE
Create a coerce operator

### ISSUE THREAD

**Issue by j-blasco** [glts/vim-radical#6]
Currently the coerce functionality is not working as expected. I have for example the following text:

'one-two-three'

If we would have a coerce operator we could do something like: crsiW:
cr: coerce
s: to snake case
iW: in Word

if I do, crs, it just fails detecting that I want to be able to do this within the word. I think this functionality could be very powerful, and the plugin seems to be very close. I wonder what would be the best approach to implement this. Thank you in advance for any advice and guidance

**Comment by glts** [comment]
I think [abolish.vim](https://github.com/tpope/vim-abolish#coercion) does this well, I use it often.

In any case this plugin is focused on transformations of integers, so this is out of scope here.

**Comment by j-blasco** [comment]
Sorry, the message was intended for that repo.
