### ISSUE TITLE
Vim radical operator 

### ISSUE THREAD

**Issue by blasco** [glts/vim-radical#7]
Could we provide an operator for these transformation? I thinking about the situation where we want to transform all numbers within a text object. We could do things like "crbif": 

crb: covert all numbers to binary representation 
if: within function

and much more. Any idea on how to approach this? 

Thank you for the advice and guidance

**Comment by glts** [comment]
Just converting what’s under the cursor has usually been good enough for me, that may be why I haven’t thought about this before. But it’s a good idea.

I’m busy with other things so won’t look into it right now. Cheers,

**Comment by j-blasco** [comment]
Sure, whenever you have the time, and just some guidance so I can help might be sufficient

**Comment by glts** [comment]
radical.vim is a small plugin that does just a few things and I consider mostly 'done'. An operator would add quite a bit of complexity. I suggest using Vim macros or a script to do bulk transformations.

Closing as out of scope.
