### ISSUE TITLE
Custom mappings

### ISSUE THREAD

**Issue by blasco** [glts/vim-radical#8]
I think I can add this functionality my self, but I'll add the issue so it gets documented. From what I see there is no way to override the current mappings, right?

**Comment by glts** [comment]
Yeah, let’s make the mappings customisable. Just wrapping the bottom block in the plugin with

    if !exists('g:radical_no_mappings') || !g:radical_no_mappings
      " ...
    endif

should be sufficient, I believe.

**Comment by blasco** [comment]
Great, I've updated the plugin and created the pull request so you can just mark this as closed and accept the changes :). Thank you for the great plugin, I'll eventually get a look into the transforming it into an operator thing

**Comment by glts** [comment]
Thank you, will merge in a minute.
